### ISSUE TITLE
Problem use docker  compose

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [maxplanck-ie/docker-parkour#7]
I want to install the docker version:
I have this versions of  docker on centos 7.0
```
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.20.1, build 5d8c71b
```
I follow the code  and I change some parameters because I have already installed  apache in my machine:

This is what  run:

```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                         PORTS                              NAMES
99404018e69b        dockerparkour_parkour-web:latest     "python manage.py ..."   7 minutes ago       Up 6 minutes                   9000/tcp                           dockerparkour_parkour-web_run_2
edea00cfe5b3        dockerparkour_parkour-web:latest     "python manage.py ..."   7 minutes ago       Restarting (0) 8 seconds ago                                      dockerparkour_parkour-web_run_1
e89b38979386        dockerparkour_parkour-nginx:latest   "/usr/sbin/nginx"        11 minutes ago      Restarting (1) 4 minutes ago                                      parkour-nginx
12adcfaaa4af        dockerparkour_parkour-web:latest     "/usr/local/bin/gu..."   11 minutes ago      Up 11 minutes                  9000/tcp, 0.0.0.0:9999->8888/tcp   parkour-web
5823979aac73        postgres:9.5                         "docker-entrypoint..."   11 minutes ago      Up 11 minutes                  0.0.0.0:5434->5432/tcp             parkour-postgres
```
I'm not able to access to the  docker web

```
cat docker-compose.yml
version: '2.1'

services:
  parkour-web:
    restart: always
    image: dockerparkour_parkour-web:latest
    container_name: parkour-web
    build: ./web
    ports:
      - 9999:8888     # Jupyter
    expose:
      - 9000          # Django
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - usr_src_app_media:/usr/src/app/media
      - usr_src_app_staticfiles:/usr/src/app/staticfiles
    links:
      - parkour-postgres:postgres
    command: /usr/local/bin/gunicorn wui.wsgi:application -w 2 -b :8000

  parkour-nginx:
    restart: always
    image: dockerparkour_parkour-nginx:latest
    container_name: parkour-nginx
    build: ./nginx
    ports:
      - 90:80         # expose ports - HOST:CONTAINER
    volumes_from:
      - parkour-web
    links:
      - parkour-web

  parkour-postgres:
    restart: always
    image: postgres:9.5
    container_name: parkour-postgres
    ports:
      - 5434:5432     # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  usr_src_app_media:
  usr_src_app_staticfiles:

```
```


[maurizio@localhost docker-parkour]$ cat docker-compose.prod.yml
version: '2.1'

services:
  parkour-nginx:
    build: ./nginx-prod
    ports:
      - 100:80
      - 445:443

```

Any idea in how to debug?
